### ISSUE TITLE
Missing string resources.

### ISSUE THREAD

**Issue by cmacfarl** [jerryhcooke/smouldering_durtles#1]
Did you add values to strings.xml, but not also to app/strings.xml.sample.txt?

![image](https://github.com/jerryhcooke/smouldering_durtles/assets/1435639/0a40ff3e-654e-4d00-b7d8-fa15986e4dd2)

Also...

![image](https://github.com/jerryhcooke/smouldering_durtles/assets/1435639/c29a60d4-0010-4074-8ed0-8fdc978de860)

This correlates with the comments I made over in the forum where perhaps a dev/release branch strategy might make some sense.   With the current approach, where strings.xml is not committed, you'll have the problem seen here keeping strings.xml and the strings.xml.sample.txt in sync.

**Comment by jerryhcooke** [comment]
I'm sorry this happened; it was related to strings I added to a UI layout.

I've restored the strings.xml to a state that matches the sample one now, so it should be fine to build again.

Regarding branch strategy, now that the build is for production, I've now got it set this way:

Master = current feature complete version, now a protected branch
Release = Will hold release versions, pull to master after a period of time
Dev = Development builds, new features, etc, pull to release once ready for deployment
