### ISSUE TITLE
Notifications might be broken

### ISSUE THREAD

**Issue by MTLVMPR** [jerryhcooke/smouldering_durtles#10]
Have not seen a single notification from Smouldering Durtles.

I have them enabled in the app and outside too

![Screenshot_20230514-193532035](https://github.com/jerryhcooke/smouldering_durtles/assets/93704391/651e4978-6e5b-4dba-9aa8-cd78ca131831)

**Comment by jerryhcooke** [comment]
Thanks for letting me know. As we move away from core app functions within the app itself and on to stuff like notifications we're moving further out of my knowledge base regarding troubleshooting, but I'll do the best I can. I suspect messing with the 'availableAt' numbers in the database might let me test.

**Comment by jerryhcooke** [comment]
There was some API version checking not in place for scheduleAlarm() which is fair enough because the requirement for SCHEDULE_EXACT_ALARM is Android 13 specific and so wouldn't have been accounted for in the old code. 

I've resolved this and chucked in some fixes for the requirement to have FLAG_IMMUTABLE set on any PendingIntent calls. I've uploaded a v1.0.2b2 version to the dev release branch, if you wouldn't mind taking a look and seeing what your experience of it is regarding notifications..

**Comment by MTLVMPR** [comment]
Updated and no notification. I don't see updated version number anywhere though. Should it say 1.0.2 in app details or "about..." menu?

**Comment by MTLVMPR** [comment]
No problem. I have lots of time during the summer. 

I reinstalled and the app didn't ask for notification permission. After giving the permission through Android settings, the notifications still didn't come through in the next hour. Was a thrilling wait tbh.

The app has 1.0.2 as it's version now in both app details and "about..."

**Comment by shayaantx** [comment]
I've been getting notifications (for reviews and what not) on latest version in releases

**Comment by jerryhcooke** [comment]
@shayaantx can I ask what version of Android your phone is on?

I'm fairly certain the notification issue was an Android 13 one specifically, at least, it seems that way.

**Comment by shayaantx** [comment]
> 

android 10/one ui 2.5

**Comment by jerryhcooke** [comment]
Thanks! @MTLVMPR are you on 13? Just curious if I'm right about the API version being the issue

**Comment by MTLVMPR** [comment]
Yeah I am on Android 13

**Comment by jerryhcooke** [comment]
Final build of 1.0.2 is complete and I've fixed all the issues apart from the second tap required to clear the dialog boxes on the advanced settings, which I'm not going to hold up on.

The Play Store listing is live with version 1.0.1, but I'll be pushing the new build ASAP!
