### ISSUE TITLE
Releases are signed with Debug key

### ISSUE THREAD

**Issue by Kaiserdragon2** [jerryhcooke/smouldering_durtles#104]
All your releases the last few days are signed with the Android Debug key and not with the signing key of v1.1.1

**Comment by jerryhcooke** [comment]
I don't recall ever having built the release versions on here using the signing key - I only use that for creating Play Store releases typically. I may have done that way back in v1.1.1 by mistake, potentially, but certainly the last half dozen versions have been built as a standard APK from Android Studio.

**Comment by Kaiserdragon2** [comment]
A signed Release would allow your app to be updated in the IzzySoft Repo. https://apt.izzysoft.de/fdroid/index/apk/com.smouldering_durtles.wk

**Comment by jerryhcooke** [comment]
Just to update on two things:

1. I've made the latest release signed.
2. The app should be in F-Droid soon, theoretically
