### ISSUE TITLE
Clicking on the bars in the "Level progression" widget brings the generic "browse / search" menu instead of filtering the selection

### ISSUE THREAD

**Issue by simias** [jerryhcooke/smouldering_durtles#11]
In Flaming Durtles when I click the various progress bars in the widget I end up on a page with all the elements referenced in the item (e.g. "all level 28 Kanji", "all level 27 vocab") grouped by SRS tier.

![Screenshot_2023-05-15-15-27-59-62_ef6d4cd9a95f31ba62591357a762129e](https://github.com/jerryhcooke/smouldering_durtles/assets/7925386/d1bac40f-438d-4281-92d9-573ecf5ee755)

In Smouldering Durtles I'm sent to the browse/search page instead, where I have to filter everything manually.

The "About" dialogue says that I'm using v1.0.1 but I'm fairly sure that I installed 1.0.2 beta2.

**Comment by jerryhcooke** [comment]
Final build of 1.0.2 is complete and I've fixed all the issues apart from the second tap required to clear the dialog boxes on the advanced settings, which I'm not going to hold up on.

The Play Store listing is live with version 1.0.1, but I'll be pushing the new build ASAP!

**Comment by simias** [comment]
I confirmed that it's fixed on 1.0.3 from the Play Store. Amazing work!
