### ISSUE TITLE
Have theme changes apply faster 

### ISSUE THREAD

**Issue by jerryhcooke** [jerryhcooke/smouldering_durtles#16]
Currently behaviour only updates live elements of the dashboard view upon leaving settings, while it would be desirable to have the dashboard elements redraw after the colours have been changed without having to close and re-open the app.

**Comment by hummusw** [comment]
Looks like this feature was implemented by commits 58ec8a8264fff62f1b9dc8e33fce443f32d47b46 and 29cc00ec8d230fff962c34581faeb41920ef1b6d, if I'm understanding the description correctly?
