### ISSUE TITLE
FR: Add setting for toast displaying alternate meanings and readings

### ISSUE THREAD

**Issue by gergelycsegzi** [jerryhcooke/smouldering_durtles#19]
Hi, I've made a pull request to the previous project to add a feature that I find important to make sure that I learn all meanings of words instead of just one. Here is the existing code, hopefully it should be easy enough to adapt: https://github.com/ejplugge/com.the_tinkering.wk/pull/2

**Comment by jerryhcooke** [comment]
Hey, thanks for sharing.

It looks simple enough to drop in, so I'll see what I can do 👍🏼
