### ISSUE TITLE
Regarding copyright notices

### ISSUE THREAD

**Issue by milopiccolo** [jerryhcooke/smouldering_durtles#2]
Hi, and thanks for your hard work so far on reviving this app!

(I am not a lawyer so please take the below with a grain of salt!)

I noticed that in [this commit](https://github.com/ejplugge/com.the_tinkering.wk/commit/156c86a7bf52de752c86385e16eff23d78550552), you removed some of the original author's copyright notices (for example, in [this file](https://github.com/ejplugge/com.the_tinkering.wk/commit/156c86a7bf52de752c86385e16eff23d78550552#diff-1e1a5b277a9629421567159ba5b16d424005613c9e6841132470e040b5a65a23)).

In my understanding, the best practice is: **don't remove any other contributor's copyright notice unless you have their express permission**! (But you are permitted to add your own copyright notice above or below theirs!)

Here is some guidance from The Linux Foundation: https://www.linuxfoundation.org/blog/blog/copyright-notices-in-open-source-software-projects says "Don’t change someone else’s copyright notice without their permission... You should not change or remove someone else’s copyright notice unless they have expressly (in writing) permitted you to do so. This includes third parties’ notices in pre-existing code."

The text of the [Apache 2.0 license](https://github.com/ejplugge/com.the_tinkering.wk/blob/master/LICENSE.md) also says "
(c) You must retain, in the Source form of any Derivative Works that You distribute, all copyright, patent, trademark, and attribution notices from the Source form of the Work, excluding those notices that do not pertain to any part of the Derivative Works."

I hope that makes sense! Let me know if I can better explain what's required, or the rationale for why things work this way. And sorry to create a bit more work for you!

Also, while you are thinking about copyright notices, you might want to consider using a more general copyright notice, like 'Copyright The Smouldering Durtles Contributors' instead of 'Copyright 2023 Jerry Cooke'. This way you won't have to change it again if you accept contributions from others! But either way is fine. The same Linux Foundation page (https://www.linuxfoundation.org/blog/blog/copyright-notices-in-open-source-software-projects) has more information on this idea.

**Comment by jerryhcooke** [comment]
Thanks for drawing my attention to that, I wasn't aware that this was a requirement of the Apache licence (should have read it more carefully!) 

I've done the following:

- Restored all the original copyright notices 
- Added new copyright notices that state "Copyright The Smouldering Durtles Contributors' as suggested
