### ISSUE TITLE
Possible progress loss

### ISSUE THREAD

**Issue by MTLVMPR** [jerryhcooke/smouldering_durtles#20]
I'm pretty sure that I've done same review pile twice for 2 separate times.

1st time was pretty much back to back. I finished a around 30 reviews but at relaxed pace. After completing I saw that it wasn't syncing them like always (I have them delayed for liberal unfo usage). There were reviews available and they were the same reviews. I thought that I must've pressed abandon session by mistake.

2nd time was just now before typing this. I started doing them outside, forgot them for a while and as I came back to them, the session was gone and I had to do the same ones again.

I don't recall this happening with the old app so could it be something with newer version how it handles sessions?

**Comment by jerryhcooke** [comment]
Hmm, I haven't changed anything in the underlying session handling other than changing JobIntentService for Workmanager, but that was an in-place upgrade largely and didn't involve any changes other than creation of a couple new handlers. 

I should have some time to do some more in-depth debugging over the next week, so I'll try and work out what could be causing this, thanks for letting me know.

**Comment by jerryhcooke** [comment]
I've tried to test this on and off between updates as best I can and I don't believe it's an issue any more since I brought SD up to commit parity with FD, but please do let me know if you see this issue again 👍🏼
