### ISSUE TITLE
Level up kanji progress indicator missing

### ISSUE THREAD

**Issue by MTLVMPR** [jerryhcooke/smouldering_durtles#22]
Feel free to separate these if needed.

Important things first: 諦観 was moved up to lvl 58 and it's not showing up in my reviews unless I go to the website to do it. Same has happened to others that are beyond my level but I've done the lesson for.

No idea why but Apprentice IV kana has their "time remaining" jump to the next row. Still lined up with the kana though.
![Screenshot_20230523-025616527~2](https://github.com/jerryhcooke/smouldering_durtles/assets/93704391/8da34007-23af-4055-bd09-75b37b34b028)

Kana seem to be missing from the level progression bars.

And last the level up line is not there on level progression kanji bar. If it's a setting then I don't know where it is. It used to show the amount of kanji needed for level up. 

![Screenshot_20230524-123334712~2](https://github.com/jerryhcooke/smouldering_durtles/assets/93704391/7d326998-a768-4098-aa21-79da8ca134b8)

**Comment by jerryhcooke** [comment]
Ah, found and fixed the progress issue - was down to the boolean hasLevelUpTarget being false for kanji subject types, I must have flipped the value when I added the bool for kana items to the subject type array initial and never noticed. 

Have fixed this and included in the next dev build which, I think, I can push out tonight.
