### ISSUE TITLE
Notifications broken in 1.0.5

### ISSUE THREAD

**Issue by MTLVMPR** [jerryhcooke/smouldering_durtles#26]
Notification permission disappeared and notifications can't be toggled on in the current version of the app. Took screenshots when updating the other phone: 

![IMG_20230526_132617_445](https://github.com/jerryhcooke/smouldering_durtles/assets/93704391/e951b64e-27a5-4ca7-9b35-a37ba8da7f47)
![IMG_20230526_132620_797](https://github.com/jerryhcooke/smouldering_durtles/assets/93704391/c4a87a97-0cac-4868-b0b2-2f7858962a6d)

**Comment by DropaBombOnEm** [comment]
Same!

**Comment by TacticalWhisky** [comment]
Same here, glad to know it's not just me. I have notifications on in SD, but Android doesn't see the permission ("This app does not send notifications") so it can't be enabled.

SD 1.05 from the Play Store, Android 13 (TQ2A.230505.002), Google Pixel 5


![Screenshot_20230526-074125](https://github.com/jerryhcooke/smouldering_durtles/assets/134707611/2ef77a5d-e285-4dac-baf6-52aafef00a36)

Everything else seems to be working great, though!

**Comment by jerryhcooke** [comment]
Have resolved this in latest build, as far as I'm aware, will be out soon!
