### ISSUE TITLE
Unnatural English on "Enter V2 API Token" screen.

App version 1.0.5

(Screenshot below)

### ISSUE THREAD

**Issue by DropaBombOnEm** [jerryhcooke/smouldering_durtles#27]
![IMG_20230527_095215.jpg](https://github.com/jerryhcooke/smouldering_durtles/assets/100824788/8b5b3abe-9f13-47c9-909c-c44e915d2fc0)

**Comment by DropaBombOnEm** [comment]
To be more clear, the highlighted "on" seems unnecessary and odd.

**Comment by jerryhcooke** [comment]
Typos! My greatest weakness! Thank you, have fixed it, hehe 😅
