### ISSUE TITLE
Widget Capitalization Inconsistency (v1.0.6)

### ISSUE THREAD

**Issue by DropaBombOnEm** [jerryhcooke/smouldering_durtles#28]
![Screenshot_2023-05-27-21-21-14-78_b783bf344239542886fee7b48fa4b892.jpg](https://github.com/jerryhcooke/smouldering_durtles/assets/100824788/add6bd24-b205-4375-a629-23d55066c6b0)

**Comment by jerryhcooke** [comment]
Doh, I fixed that in one of the betas, and have clearly managed to unfix it! Good looking out, I've fixed it again and it'll be in the next update! 👍🏼
