### ISSUE TITLE
Level progression bars

### ISSUE THREAD

**Issue by alphaMJL** [jerryhcooke/smouldering_durtles#29]
Right is flamming, left is smoldering. Progress bars not showing correctly. 

![20230531_210047](https://github.com/jerryhcooke/smouldering_durtles/assets/70593493/f4e0d17b-6d19-417b-8c05-3c30c7d4daed)

**Comment by alphaMJL** [comment]
Seems to only affect the wanikani theme

**Comment by jerryhcooke** [comment]
This is due to a hex code typo, it's fixed in the new release.
