### ISSUE TITLE
Build error: resource not found string/labelDebug

### ISSUE THREAD

**Issue by allthefaults** [jerryhcooke/smouldering_durtles#33]
Hey,

I've been trying to build this version in Android Studio to have a little play with how to implement some features, but I'm a bit lost at this error. I'm not sure what this line is referencing, so I can't find a way to fix it. Any ideas?

![image](https://github.com/jerryhcooke/smouldering_durtles/assets/48826934/c4643284-0bf2-474a-a899-539f8e3a961c)

The file throwing the error:
![image](https://github.com/jerryhcooke/smouldering_durtles/assets/48826934/157d38b7-469a-4363-a9f2-6c96ab36819d)

**Comment by jerryhcooke** [comment]
The values.xml file is generated automatically as part of the Gradle build process. 

It's looking for @string/labelDebug which is located in the strings.xml 

I've noticed that for whatever reason the updated strings.xml sample was never merged in and so the one you've created may miss this. Add this line under your appLabel line:

<string name="labelDebug">DEBUG: App Name</string>

That should resolve it, but I've had some issues in the past where it doesn't like it, in which case I usually temporarily edit the build.gradle file to not use a string reference and instead just type it in 😅
