### ISSUE TITLE
[Feature Request] Monochrome Icon for Smouldering Durtles

### ISSUE THREAD

**Issue by the-wright-jamie** [jerryhcooke/smouldering_durtles#35]
As of Android 12, Android supports monochrome icons on the home screen which are reactive to the user's selected colour scheme (Material You).

I'm on a bit of a mission to get as many of my home page icons to support this functionality as possible and would love to contribute to this project, so if you could provide me with the source document for the icon (png, psd, whatever has the highest quality version) I can contribute the needed patch to add this functionality. 

For example:
![Screenshot_20230801-151502](https://github.com/jerryhcooke/smouldering_durtles/assets/121819290/b21b2c81-a255-45cd-8dcb-0354f3423d25)

Here, the only app to support themed icons is Kanji Study. It would be great, and a nice little attention to detail effect if Smouldering Durtles also included this 🙂.

As I said, I can provided the change myself, but it would be made easier with access to the original images for the icon.

**Comment by jerryhcooke** [comment]
Thanks for your work on this, the PR is merged and the new build is in the releases and will be on the play store soon. 

I've provided thanks to you in the descriptions of both :)

**Comment by the-wright-jamie** [comment]
I saw my name in the release notes :-) thanks for your work on this
