### ISSUE TITLE
New Items added to previously completed levels clutters the dashboard

### ISSUE THREAD

**Issue by Cammymoop** [jerryhcooke/smouldering_durtles#38]
It's been bothering me for awhile but this recent batch of new items really got me.

![Screenshot_20230816_154208_Smouldering Durtles](https://github.com/jerryhcooke/smouldering_durtles/assets/6477924/618c69ca-58ef-42ff-8451-8ccd58c1cb68)

**Comment by FelixNemis** [comment]
Created a PR #39 that fixes this by adding an option to limit how many levels backwards to die progress bars for.

**Comment by jerryhcooke** [comment]
Thanks for your work on this, the PR is merged and the new build is in the releases and will be on the play store soon.

I've provided thanks to you in the descriptions of both 😀
