### ISSUE TITLE
Issue updating to 1.0.9

### ISSUE THREAD

**Issue by machinaeZER0** [jerryhcooke/smouldering_durtles#56]
I'm on a pixel 4a, attempting to update my 1.0.8 install using the GitHub release apk. This is the popup I get when I selected "update" from the initial Android popup:

![Screenshot_20231107-151733.png](https://github.com/jerryhcooke/smouldering_durtles/assets/3624023/7f517250-5594-4815-8654-ee2f46066f23)

Any idea why this would be the case? None of the previous releases had this issue, and were all performed over existing installs. Let me know if I can help troubleshoot?

**Comment by jerryhcooke** [comment]
I'm not sure why that's the case - an update should typically occur provided the codebase change is small enough. That said, I had the same experience and I'm conscious that when testing a few of the changes required a reinstall, so I'm not surprised. I'd suspect a signature mismatch, as the most common reason for an update not applying, but I only ever code on my Mac Mini at home or my MBP at work, and they're both using the same keystone. 

I know it's a tad annoying, but it's also the reason I added the settings backup - I'd recommend just exporting and updating with a reinstall. 

I don't believe this is a bug, so closing the issue, but if you believe there's more to investigate, let me know 👍🏼

**Comment by jerryhcooke** [comment]
Just to update, I found the same issue with the Play store version and though confusing (because I’d have expected the Play Console to have detected any signature mismatches) I’ve built a fresh APK and bundle on my MacMini, which is where I’ve done most releases, and replaced the release on here with the Play version in review.

**Comment by machinaeZER0** [comment]
Thank you!
