### ISSUE TITLE
Dashboard timeline scroll seems broken in 1.0.9

### ISSUE THREAD

**Issue by machinaeZER0** [jerryhcooke/smouldering_durtles#57]
I recently realized I could set a larger timeline chart size and a smaller "part of timeline chart shown at once" in the dashboard settings, allowing me to (for example) show 12 hours of timeline at a time, but scroll the chart horizontally across as much as 14 days(!)

This behavior seems to have broken in 1.0.9, as attempting to scroll the timeline (right to left) seems to trigger a new gesture behavior that started a review session. Would it be possible to allow scrolling through the timeline chart again? (also, is it possible to disable the gesture mentioned above on the dashboard?)

Let me know if you need additional info! Testing the latest Play version on Android (Pixel 4a).

**Comment by jerryhcooke** [comment]
This appears to be an unintended result of [PR #49](https://github.com/jerryhcooke/smouldering_durtles/pull/49), in which @shocklateboy92 added swipe to start gesture navigation. 

Would be good to make this option, I think, and to attempt to exclude the timeline view from responding to it, to avoid breaking that interaction.

**Comment by shocklateboy92** [comment]
Ah, so **that's** what the `NestedScrollView` was for.  I didn't know how to enable this feature.

**Comment by jerryhcooke** [comment]
Oh for the ease of PowerApps element ordering.

I'm sure there's a way to include a child horizontal scrolling element inside a parent that is watching for horizontal gestures, may just require some tinkering. 

I'll have a read through this in a bit: https://medium.com/androiddevelopers/gesture-navigation-handling-gesture-conflicts-8ee9c2665c69

**Comment by jerryhcooke** [comment]
Just giving it some thought, may be as easy as just sticking an override on the gesture detection for the TimeLineBarChartView - I'll give it a whirl when I get into the office this morning

**Comment by jerryhcooke** [comment]
Fixed in 1.1.0 with the roll back of the swiping feature; something to potentially revisit in future, but would require a major alteration to the main activity layout, as far as I can tell
