### ISSUE TITLE
Undo button sometimes doesn't work in latest version 

### ISSUE THREAD

**Issue by Austin-Scott** [jerryhcooke/smouldering_durtles#64]
Most of the time the "undo" button still works but sometimes when I tap on it nothing will happen. I can get around this by tapping on the "skip" button and then re-tapping on the "undo". I unfortunately don't know how to reliability recreate this issue as it seems to happen at random. Anyone else experiencing this?

**Comment by jerryhcooke** [comment]
Hi Austin,

I believe, though I'm unable to verify, that this was the result of the changed view type in the last version to facilitate swipe behaviours. I've rolled these back, and hope that this will resolve the issue.

**Comment by Austin-Scott** [comment]
Still experiencing this issue in version 1.1.1, I'm going to downgrade to 1.0.7 and report back in a few days if that causes the problem to go away.

**Comment by Austin-Scott** [comment]
Also to elaborate on the original issue, I've since noticed that sometimes the skip button will stop working too and even sometimes both buttons will fail to do anything.

**Comment by Austin-Scott** [comment]
I use anki mode reviews with the "delay processing quiz results" option enabled.

**Comment by Austin-Scott** [comment]
@jerryhcooke This problem is not present in version 1.0.7, so this should still be an open issue
