### ISSUE TITLE
Can't set api token

### ISSUE THREAD

**Issue by Togtja** [jerryhcooke/smouldering_durtles#67]
When attempting to set the API token it just brings me back to the same page.

Note the api token has been expired
If going into settings and setting the api token it seems to set, but leaving and entering the settings menu seems to unset it again 
![Screenshot_20240102-183519](https://github.com/jerryhcooke/smouldering_durtles/assets/33124639/4a8bf67c-91e5-4c1d-8842-3af10c42238e)
![Screenshot_20240102-183531](https://github.com/jerryhcooke/smouldering_durtles/assets/33124639/187332d9-7fad-4b34-a115-ec45bd699a17) 
![Screenshot_20240102-183539](https://github.com/jerryhcooke/smouldering_durtles/assets/33124639/ad1a2321-e791-4553-ad3d-46ca1aed5980)
)

**Comment by jerryhcooke** [comment]
It's possible that this issue has been resolved with the latest theme switching logic fix (this was introducing an interruption on screen switch that appears to have affected a number of preferences pages) so could you please test and see if you still experience this?

**Comment by Togtja** [comment]
That seem to have done the trick thanks so much for you work in this app!
