### ISSUE TITLE
"Previous" button has no text

### ISSUE THREAD

**Issue by hummusw** [jerryhcooke/smouldering_durtles#72]
In version 1.1.0, the previous button doesn't seem to have text anymore:
![image](https://github.com/jerryhcooke/smouldering_durtles/assets/16628437/e980ad1a-c215-4352-af6a-8c50f30ce90e)

Rolling back to version 1.0.9, the previous button worked normally:
![image](https://github.com/jerryhcooke/smouldering_durtles/assets/16628437/edb05d9c-bd63-49bb-b8d8-e634d162a294)

**Comment by jerryhcooke** [comment]
Included this in the new build, pushing now ^-^
