### ISSUE TITLE
Swiping left in lessons no longer goes back to previous item

### ISSUE THREAD

**Issue by hummusw** [jerryhcooke/smouldering_durtles#74]
Swiping left in lessons now does nothing in v1.1.0. This used to go back to the previous lesson item in Flaming Durtles and previous versions of Smouldering Durtles.

**Comment by jerryhcooke** [comment]
Doh, entirely my bad - I was clearly overzealous in removing the problem swipe behaviour from 1.0.9 to fix the scroll issues. 

I'll compare the pre-1.0.9 code and restore the swiping logic that was present there.

**Comment by hummusw** [comment]
No worries, I'm quite familiar with making overzealous changes and subsequently reverting some of them myself :)
Thanks for taking the time to review my many pull requests!

**Comment by jerryhcooke** [comment]
Included this in the new build, pushing now ^-^
