### ISSUE TITLE
SRS stage indicator slightly out of frame

### ISSUE THREAD

**Issue by hummusw** [jerryhcooke/smouldering_durtles#76]
As reported on the forums, the SRS stage indicator is slightly out of frame after answering a question and going to the info screen (when lightning mode is off, either manually or on an incorrect answer).

See original post [here](https://community.wanikani.com/t/android-smouldering-durtles-v110-native-app-with-offline-lessons-and-reviews-plus-themes-and-script-like-features/61776/263)

**Comment by jerryhcooke** [comment]
Included this in the new build, pushing now, thanks for fixing!
