### ISSUE TITLE
[Feature Request] Add "Pattern of Use" Content?

### ISSUE THREAD

**Issue by machinaeZER0** [jerryhcooke/smouldering_durtles#85]
The context sentences are always super helpful, but I miss seeing the "Pattern of Use" phrases when I study in Smouldering Durtles:
![image](https://github.com/jerryhcooke/smouldering_durtles/assets/3624023/81fc7ce9-b933-4511-9a40-b46e6839d4ba)

I have a feeling these are stored in a way that may be harder to extract/import into the app, but if it were possible to do I would love to see it happen someday :)

**Comment by AquilaFasciata** [comment]
To the best of my knowledge, it doesn't appear that the API exposes this information -- the only way to implement this would be to scrape it from the website [which is against their ToS](https://www.wanikani.com/terms#c-acceptable-use).
