### ISSUE TITLE
Error in link on Support/Feedback page

### ISSUE THREAD

**Issue by gorak** [jerryhcooke/smouldering_durtles#88]
On the Support/ Feedback page:

If you are having problems with this app, the best way to get support is to post to the support _thread on the forums_.

The link points to an invalid URL: https://www.jhcooke.com.com/

This should be corrected to: https://community.wanikani.com/t/android-smouldering-durtles-v111-native-app-with-offline-lessons-and-reviews-plus-themes-and-script-like-features/

Perhaps an additional paragraph could be added:

You can also report bugs and make feature requests on the _Git Hub pages for the project_.

With a link to: https://github.com/jerryhcooke/smouldering_durtles/issues

Thanks!

**Comment by jerryhcooke** [comment]
Thank you for pointing this out!

I'll change this in the next update - I'm also aware that the contact information is a little bit inconsistent and I need to make it all align 😅

**Comment by jerryhcooke** [comment]
Hiya, 

I can confirm that I've fixed this in the most recent update. 

All the best, 

Jerry

**Comment by gorak** [comment]
Awesome, great work!Cheers,JamieSent from my Galaxy
-------- Original message --------From: Jerry Cooke ***@***.***> Date: 22/12/2024  21:47  (GMT+08:00) To: jerryhcooke/smouldering_durtles ***@***.***> Cc: Jamie Thom ***@***.***>, Author ***@***.***> Subject: Re: [jerryhcooke/smouldering_durtles] Error in link on Support/Feedback page (Issue #88) 
Hiya,
I can confirm that I've fixed this in the most recent update.
All the best,
Jerry
