### ISSUE TITLE
Characters text colour is effected by High contrast text

### ISSUE THREAD

**Issue by Togtja** [jerryhcooke/smouldering_durtles#89]
If are running a dark theme where the type colour is put on the characters themselves, if you enable "High Contrast Text", the colour will disappear and become either black or white (what ever the RGB value is closest to) 

Example:
![image](https://github.com/user-attachments/assets/94d0df46-a3ed-446b-9afb-26e88d6d569d)

Vs how it is supposed to be:
![image](https://github.com/user-attachments/assets/b632d3e6-e8c2-4d10-94ba-14b65117f53d)

I have created a fix based on the SO question here
https://stackoverflow.com/questions/54599485/how-to-ignore-high-contrast-accessibility-option-in-android-during-canvas-drawin
So, you'll see a PR very soon

**Comment by jerryhcooke** [comment]
This was included in build 1.1.5, thank you for your work :)
