### ISSUE TITLE
Widgets not displaying lesson and/or review count.

### ISSUE THREAD

**Issue by DropaBombOnEm** [jerryhcooke/smouldering_durtles#9]
Adding a widget to your home screen doesn't do much other than add a dark-grey square that will take you to the app when clicked.
![IMG_20230513_181625](https://github.com/jerryhcooke/smouldering_durtles/assets/100824788/d1d5ae46-1f6b-46c3-b2c7-8d73b44cad2f)

**Comment by jerryhcooke** [comment]
Thanks for letting me know! Widget are an area I'm very unfamiliar with (context: I've never coded with Java before this or done any Android app making) but I'll do my best to get it working in the next realise after v1.0.2

**Comment by DropaBombOnEm** [comment]
Oh, just one more minor request 😅

If/when you restore the functionality, can you make both of the words capitalized? 

For example "Lessons/Reviews") instead of "Lessons/reviews" (the original)

**Comment by jerryhcooke** [comment]
Sure thing!

**Comment by jerryhcooke** [comment]
### RESOVLED

The onEnabled, onRestored, etc. methods all call processAlarmWithWakeLock() - however only processAlarm() had a call to updateWidgets() in it, resulting in the only one action from the app (hitting top of the hour and triggering a review notification check) caused the widget to update gain after being recreated upon exiting the app. 

Added a call to updateWidgets() to processAlarmWithWakeLock() resolved this issue and the widgets now show data correctly.
