### ISSUE TITLE
Allow to download a single audio file on the fly

### ISSUE THREAD

**Issue by marcellonobili** [jerryhcooke/smouldering_durtles#92]
I sometimes check out words of a level well above or below my current level, for which the bulk of audio files has not been downloaded, has been downloaded on a different device or is missing after a reinstall.

I think it would be nice to show the play button anyway, and download the single audio file on the fly with a little loading indicator on the button itself while doing so, then play the audio once finished.

I am an Android developer and I would be glad to look into it and create a PR if you think it would be an useful addition.

**Comment by jerryhcooke** [comment]
Hi Marcello, 

Sorry for the delay in responding to this - I'd had the back-to-back combination of having two weeks of jury duty followed by starting my new development role and therefore have had very little time to look at anything. 

I'm not sure about downloading individual ones as that would require some tinkering with the code for downloading audio files, but given that the audio file is directly linked in the data structure for the subject, I guess it's probably easy enough to have the audio button react as:

If (Downloaded = True) Play Cached File
Else Stream Audio

Given that the audio button is already displayed contingent on the download status, putting that logic in shouldn't be very difficult I'd hope. I've had another couple small requests to tinker with the subject info page, so I suspect I could probably do this all as part of the same work.

**Comment by jerryhcooke** [comment]
This was as easy to implement as I thought, so it will be in the next release :)

**Comment by marcellonobili** [comment]
Hi Jerry, sorry for the late reply! Thank you very much, I think it's a great solution!
