### ISSUE TITLE
Feature request: Allow users to pick colours by entering exact hex code

### ISSUE THREAD

**Issue by peepincreepin** [jerryhcooke/smouldering_durtles#95]
As title says. I like to sign the colours in the app to what's in WaniKani, and it's difficult to do so with the current slider system. For anyone who wants to charge the colours, please allow entry of hex codes / rgb values.

**Comment by jerryhcooke** [comment]
The default light mode colours, while not a perfect hex match for the shades WaniKani use, are close enough as makes largely no difference, while being slightly higher contrast given the context. 

![image](https://github.com/user-attachments/assets/30827933-227f-4589-91a3-6dd20955b07c)

I made a tool a while back to make it easier to visualise when making custom themes with hex values, as a matter of fact, which I can always pop in a repo when I next get a chance to check it still makes the array correctly. 

![image](https://github.com/user-attachments/assets/546dd9bc-906b-4bb3-837f-46cd891e46f6)

**Comment by peepincreepin** [comment]
Unfortunately I don't use light mode; it hurts my eyes. It would be nice if one of the dark mode themes had the default WK colours too.

**Comment by peepincreepin** [comment]
Or if there were an easy button to press to just align to the WK colours
